apiVersion: apps/v1
kind: Deployment

metadata:
  name: app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
      
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: app
          image: 017520465419.dkr.ecr.us-east-1.amazonaws.com/images-Repository:app
          ports:
            - containerPort: 8085
          